/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package seagulldockapp;

import java.util.ArrayList;//imports the arraylist
import javax.swing.JOptionPane; //allows JOptionPane

/**
 *
 * @author Sophie Quinn
 */
public class SDGUI extends javax.swing.JFrame {
    CommonGullSSL myCGull = new CommonGullSSL(); //imports the CommonGull SSL
    HerringGullSSL myHGull = new HerringGullSSL();//imports the HerringGull SSL
    ArrayList incomingMessages = new ArrayList<>();//imports the incomingMessagesQueue
    ArrayList RecentAdoptions = new ArrayList<>();//imports the recentAAdoptionsStack
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SDGUI.class.getName());

    /**
     * Creates new form SDGUI
     */
    public SDGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        commonGullBtn = new javax.swing.JRadioButton();
        herringGullbtn = new javax.swing.JRadioButton();
        SeagullList = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        SeagullDetailsBox = new javax.swing.JTextArea();
        ChooseGullLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        UpForAdoptionLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        RecAdoptSeagulls = new javax.swing.JList<>();
        RecAdoptLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Messagesbtn = new javax.swing.JButton();
        Submitbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(commonGullBtn);
        commonGullBtn.setText("Common Gull");
        commonGullBtn.addActionListener(this::commonGullBtnActionPerformed);

        buttonGroup1.add(herringGullbtn);
        herringGullbtn.setText("Herring Gull");
        herringGullbtn.addActionListener(this::herringGullbtnActionPerformed);

        SeagullList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        SeagullList.addActionListener(this::SeagullListActionPerformed);

        SeagullDetailsBox.setColumns(20);
        SeagullDetailsBox.setRows(5);
        jScrollPane1.setViewportView(SeagullDetailsBox);

        ChooseGullLabel.setText("Please choose a species of gull:");

        UpForAdoptionLabel.setText("Seagulls up for adoption:");

        RecAdoptSeagulls.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Barty", "Soho", "Lilly", "Flop", "Cranky", "Flop2", "AteMyChip", "Sunshine", "Hangry", "BigGuy" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(RecAdoptSeagulls);

        RecAdoptLabel.setText("Recently Adopted Seagulls:");

        Messagesbtn.setText("Messages");
        Messagesbtn.addActionListener(this::MessagesbtnActionPerformed);

        Submitbtn.setText("Submit");
        Submitbtn.addActionListener(this::SubmitbtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ChooseGullLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(SeagullList, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(UpForAdoptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(herringGullbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(commonGullBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RecAdoptLabel))
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Messagesbtn)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))))
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(Submitbtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(ChooseGullLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commonGullBtn)
                    .addComponent(Messagesbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(herringGullbtn)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UpForAdoptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(SeagullList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Submitbtn)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(RecAdoptLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //if the user selects the herring gull option
    private void herringGullbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_herringGullbtnActionPerformed
        //I was not able to implement my SSLs to integrate with the GUI, 
        //I created the display of how the GUI would look once these radio buttons were clicked.
        
        //removes all items so they do not stack on top
        //of each other with multiple radio button clicks
        SeagullList.removeAllItems();
        SeagullList.addItem("Seagull #5");
        SeagullList.addItem("Seagull #6");
        SeagullList.addItem("Seagull #7");
        SeagullList.addItem("Seagull #8");
         
        //the default seagull that will appear on the dropdown once this radio button is clicked.
        SeagullList.setSelectedItem("Seagull #5");
         
        //text that displays in the text box at the bottom of the GUI
        SeagullDetailsBox.setText("     Herring Seagull data will be displayed here,\n     including it's size and name.");
    }//GEN-LAST:event_herringGullbtnActionPerformed

    //if the user selects the common gull option
    private void commonGullBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commonGullBtnActionPerformed
       //I was not able to implement my SSLs to integrate with the GUI, 
        //I created the display of how the GUI would look once these radio buttons were clicked.
        
        //removes all items so they do not stack on top
        //of each other with multiple radio button clicks
        SeagullList.removeAllItems();
 
        SeagullList.addItem("Seagull #1");
        SeagullList.addItem("Seagull #2");
        SeagullList.addItem("Seagull #3");
        SeagullList.addItem("Seagull #4");
         
        //the default seagull that will appear on the dropdown once this radio button is clicked.
        SeagullList.setSelectedItem("Seagull #1");
         
        //text that displays in the text box at the bottom of the GUI
        SeagullDetailsBox.setText("     Common Seagull data will be displayed here,\n     including it's size and name.");
    }//GEN-LAST:event_commonGullBtnActionPerformed

    private void SeagullListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeagullListActionPerformed
       
        //details about the chosen seagull appear in this text box.
        
    }//GEN-LAST:event_SeagullListActionPerformed

    private void MessagesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MessagesbtnActionPerformed
        
        //creates a popup window to display messages from the queue to the user
        JOptionPane.showMessageDialog(null, "Welcome to your messages! No new messages yet..");
        
    }//GEN-LAST:event_MessagesbtnActionPerformed

    private void SubmitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitbtnActionPerformed

        //once this button is pressed, the chosen seagull would
        //be removed from their respective SSL and placed inside
        //the RecentlyAdopted stack.
     if (SeagullDetailsBox.getText().isEmpty()) {
        //if the text box has nothing, there will be no popup window
    } else {//if there is text, the window will popup
        JOptionPane.showMessageDialog(null, "Submitted!");
    }

    }//GEN-LAST:event_SubmitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SDGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChooseGullLabel;
    private javax.swing.JButton Messagesbtn;
    private javax.swing.JLabel RecAdoptLabel;
    private javax.swing.JList<String> RecAdoptSeagulls;
    public javax.swing.JTextArea SeagullDetailsBox;
    private javax.swing.JComboBox<String> SeagullList;
    private javax.swing.JButton Submitbtn;
    private javax.swing.JLabel UpForAdoptionLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton commonGullBtn;
    private javax.swing.JRadioButton herringGullbtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
